# **HOMEWORK 3...?** 🕵
## **DUE: *October 21, 2025 @ 11:59 PM***
## **24-HR LATE DUE DATE W/ A 15% PENALTY: *October 22, 2025 @ 11:59 PM***

### **DO NOT REMOVE ANY PART OF ANY OF THE QUESTIONS OR YOU LOSE CREDIT**
### *No Hardcoding Any Part of Any Question*  😋🪄🧌
### **REMEMBER TO SHOW ALL CODE OUTPUT (NO CREDIT OTHERWISE)**
### **Reminder: Use tools or websites such as https://www.convert.ploomber.io/ to create a clean PDF from jupyter, check piazza for more details**
### **Reminder: Please make sure your code runs before submitting your work. Code sections that do not run will receive 0 credits, no partials will be given. This is VERY important in real project development.**

---
---
**DISCLAIMER: This is a fake story, not a real incident! We have created this story just for the data exploration purpose.**

---
---

**Campus Police Department**

Incident Report

---

**Incident Date:** September 27, 2025

**Location of Incident:** 2nd Floor, Iribe Building

**Items Left at the Scene:** Red Ticket for Zichao's Magic Show

**Case Number:** 2025-IRB-0027

---
**Victim Information:**

**Name:** Dr. Fardina Alam

**Affiliation:** University of Maryland, College Park

**Position:** Professor

**Contact Information:** fardina@umd.edu

---

**Incident Description:**

On the evening of September 27, 2025, an unknown individual(s) unlawfully entered Dr. Fardina's room located on the 2nd floor of Iribe and stole a set of Markers. The stolen items were a set of limited edition markers that Dr. Fardina had spent years collecting. At the scene of the crime, a red entry ticket for "Zichao's Magic Show" was found on the floor near Dr. Fardina's desk.

In [96]:
# We import all essential libraries for this HW.
# If you want to add additional libraries, you can add more here!
import pandas as pd
from datetime import datetime
import string

## YOUR TASK 🔎:

In this assignment, you are tasked with solving the mystery of Dr. Fardina's stolen markers and finding the culprit.

* To accomplish this, you will be provided with **4 data sets** containing key information related to the incident. The list of the data sets name given below:

 - Profiles
 - Witnesses
 - Zichao's magic show
 - Interrogation Statements



* Your goal is to analyze these data sets to uncover the clues and evidences that will lead you to the thief.

**Be careful in following instructions as it may lead to you losing points :(**

Take a moment to look at all the data sets below:

---

**Profiles:**

This dataset contains information regarding all the potential people that could have committed the crime. General information regarding each person are as follows:
- `ID`: A **unique** identification for each person
- `Name`: The name of the person
- `Birthday`: The birthday of the person
- `Location_during_crime`: The location of the person during the crime
- `Eye_Color`: The eye color of the person
- `Skin_Color`: The skin color of the person
- `Hair_Color`: The hair color of the person
- `Height`: The height of the person in cm

**Witnesses:**

This dataset contains a statement from everyone in profiles, regarding suspicious things they saw during the time of the crime. Information that comes in this dataset are as follows:
- `ID`: A **Unique** identification for each person
- `Statement`: A statement from the person regarding a suspicious activity during the time of the crime

**Zichao's Magic Show:**

This dataset contains everyone that purchased a ticket for the show. **NOTE** that not everyone in profiles has purchased a ticket for this show. The Information contained in this dataset are as follows:
- `ID`: A **Unique** indentification for each person
- `Ticket_Number`: A **Unique** number that serves as an identification for the ticket bought

**Interrogation Statements:**

This datasets contains a statement from each person after they have been interrogated. **NOTE** assume that each statement is ***100% true*** and that ***there are people in this dataset who aren't in the "Profiles" dataset***.
Information contained in this dataset are as follows:

- `Name`: The name of the person being interrogated
- `Statement`: A statement the person gives after being interrogated

---

## Q1) Lets begin by observing the profiles dataset (10 PTS Total)


**TASK 1.1 (1 Point):**  In the code box below, load in `Profiles` dataset into a variable called `profiles_df` and display it

**Outputs to be Graded:**
- Variable(s): `profiles_df`
- Cell outputs

In [97]:
profiles_df = pd.read_csv('Profiles.csv')
profiles_df

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height
0,P299,Marco Rossi,1969/07/10,fourth floor,red,indigo,orange,191
1,P086,Aarav Patel,1979/03/10,second floor,indigo,indigo,green,198
2,P022,Li Wei,1990/10/08,fourth floor,blue,red,violet,154
3,P003,Haruto Tanaka,1996/27/10,lobby,green,blue,violet,158
4,P036,Kwame Mensah,1991/26/02,fourth floor,blue,yellow,orange,184
...,...,...,...,...,...,...,...,...
343,P126,Andrew Choe,1988/03/01,NaN,violet,indigo,red,176
344,P203,Krish Thakker,1965/26/09,third floor,yellow,indigo,orange,193
345,P273,Jeonghan Yoon,2003/12/07,fourth floor,blue,indigo,red,193
346,P290,Ananya Malipeddi,10/03/1994,third floor,NaN,yellow,indigo,161
347,P233,Ifra Syed,06/27/1982,second floor,red,yellow,orange,169

**TASK 1.2 (1 Point):**  Next, you need to display the number of rows and columns in the `profiles_df` dataframe.

**Outputs to be Graded:**
- Cell outputs

In [98]:
profiles_df.shape

(348, 8)

**TASK 1.3 (1 Point):**  Next, you need to display the name of the columns in the `profiles_df` dataframe.

**Outputs to be Graded:**
- Cell outputs

In [99]:
profiles_df.columns

Index(['ID', 'Name', 'Birthday', 'Location_during_crime', 'Eye_Color',
       'Skin_Color', 'Hair_Color', 'Height'],
      dtype='object')

**TASK 1.4 (1 Point):**  Now, you need to display the types of the columns in the `profiles_df` dataframe.

**Outputs to be Graded**
- Cell outputs

In [100]:
profiles_df.dtypes

ID                       object
Name                     object
Birthday                 object
Location_during_crime    object
Eye_Color                object
Skin_Color               object
Hair_Color               object
Height                    int64
dtype: object

**TASK 1.5 (2 Points):**
- Utilizing the `count()` function on this dataset and set it to the variable `info` and then display it.
- Write any **potential problem** that you see with the dataset when observing the output of the count function:

**Outputs to be Graded**
- Variable(s): `info`
- Cell outputs
- Written statement(s) describing potential problem(s)

In [101]:
info = profiles_df.count()
info

ID                       348
Name                     348
Birthday                 348
Location_during_crime    280
Eye_Color                280
Skin_Color               348
Hair_Color               348
Height                   348
dtype: int64

**<font color='red'>Write your observations here:</font>**

There are 68 missing entreis in both the eye_color and location_during_crime columns. This could cause issues when filtering suspects based on these criteria.

**TASK 1.6 (4 Points):**

Look back at the "Profiles" dataset. Using other pandas functions than `count()`, **can you spot another potential problem with the dataset?**

**Outputs to be Graded**
- Written statement(s) describing your observations

In [102]:
print(profiles_df.describe())
print(profiles_df['ID'].duplicated().any())

           Height
count  348.000000
mean   175.425287
std     15.539951
min    150.000000
25%    161.000000
50%    175.000000
75%    190.000000
max    200.000000
True

**<font color='red'>Write your observations here:</font>**

There are duplicate IDs in the data set which is a problem beause they are supposed to be unique identifiers. Also, visually I can just see that the dates for birthdays appear in a variety of formats.

## Q2) Cleaning the data set (25 PTS Total)

**TASK 2.1 (10 Points):** Lets begin by fixing the Birthday column. You may notice that the dates are in inconsistent format!

- Pandas internally represent dates in 'datetime64' format which is a form of ISO 8601. Basically, dates are represented as yyyy-mm-dd.


- Fix all the dates in the Birthday Column of `profiles_df` dataframe (Do not use other variable name).
- Display the `profiles_df` dataframe after you are done.
- Note that the only **2 formats** the dates are in is either **yyyy/dd/mm** or **mm/dd/yyyy**;
- You want to represent them as **yyyy-mm-dd**

- **EXAMPLE**: In the “Profiles” dataset, dates like *2000/10/12* and *10/12/2000* follow different formats—one as *December 10th, 2000*, and the other as *October 12th, 2000*. We aim to standardize them to *2000-12-10* and *2000-10-12*, respectively.

**HINT:** some datetime functions might make things easier.
- https://www.geeksforgeeks.org/python-pandas-to_datetime/
- https://www.programiz.com/python-programming/datetime/strftime

**Outputs to be Graded**
- Variable(s): `profiles_df`
- Cell outputs

In [103]:
import pandas as pd

def fix_date(date):
    try:
        dt = pd.to_datetime(date, format='%Y/%d/%m', errors='raise')
    except:
        try:
            dt = pd.to_datetime(date, format='%Y/%m/%d', errors='raise')
        except:
            dt = pd.to_datetime(date, format='%m/%d/%Y', errors='coerce')
    return dt.strftime('%Y-%m-%d')

profiles_df['Birthday'] = profiles_df['Birthday'].apply(fix_date)
profiles_df

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height
0,P299,Marco Rossi,1969-10-07,fourth floor,red,indigo,orange,191
1,P086,Aarav Patel,1979-10-03,second floor,indigo,indigo,green,198
2,P022,Li Wei,1990-08-10,fourth floor,blue,red,violet,154
3,P003,Haruto Tanaka,1996-10-27,lobby,green,blue,violet,158
4,P036,Kwame Mensah,1991-02-26,fourth floor,blue,yellow,orange,184
...,...,...,...,...,...,...,...,...
343,P126,Andrew Choe,1988-01-03,NaN,violet,indigo,red,176
344,P203,Krish Thakker,1965-09-26,third floor,yellow,indigo,orange,193
345,P273,Jeonghan Yoon,2003-07-12,fourth floor,blue,indigo,red,193
346,P290,Ananya Malipeddi,1994-10-03,third floor,NaN,yellow,indigo,161
347,P233,Ifra Syed,1982-06-27,second floor,red,yellow,orange,169

**TASK 2.2 (5 Points):** Now that we have cleaned up the Birthday column, lets find the age of each person. Create a new column called `Age` that displays the age of the person **on the day of the crime.** Once you are done, display the
`profiles_df` dataframe

**Outputs to be Graded**
- Variable(s): `profiles_df`
- Cell outputs

In [104]:
from datetime import datetime

crime_date = datetime(2025, 9, 27)

profiles_df['Birthday'] = pd.to_datetime(profiles_df['Birthday'])

profiles_df['Age'] = (
    crime_date.year - profiles_df['Birthday'].dt.year
    - ((crime_date.month < profiles_df['Birthday'].dt.month) | 
       ((crime_date.month == profiles_df['Birthday'].dt.month) & 
        (crime_date.day < profiles_df['Birthday'].dt.day)))
)

profiles_df

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height,Age
0,P299,Marco Rossi,1969-10-07,fourth floor,red,indigo,orange,191,55
1,P086,Aarav Patel,1979-10-03,second floor,indigo,indigo,green,198,45
2,P022,Li Wei,1990-08-10,fourth floor,blue,red,violet,154,35
3,P003,Haruto Tanaka,1996-10-27,lobby,green,blue,violet,158,28
4,P036,Kwame Mensah,1991-02-26,fourth floor,blue,yellow,orange,184,34
...,...,...,...,...,...,...,...,...,...
343,P126,Andrew Choe,1988-01-03,NaN,violet,indigo,red,176,37
344,P203,Krish Thakker,1965-09-26,third floor,yellow,indigo,orange,193,60
345,P273,Jeonghan Yoon,2003-07-12,fourth floor,blue,indigo,red,193,22
346,P290,Ananya Malipeddi,1994-10-03,third floor,NaN,yellow,indigo,161,30
347,P233,Ifra Syed,1982-06-27,second floor,red,yellow,orange,169,43

**TASK 2.3 (10 Points):** Now that we have created the `Age`; lets clean the `Eye_Color` column.

***Please read the directions carefully:***


- In order to fill in the missing eye colors, we want to find the **most common eye color** among those who have the **same hair and skin color**.
- For instance, if we want to find the eye color of someone who has yellow hair and violet skin:
 - we would first find everyone who has the same hair and skin color, in this case it would be yellow hair and violet skin
 - and then we find the most common eye color among them.
 - we then replace the missing eye color with the eye color that is the most common among the people with the same hair and skin color.
- Watch out for redundant data!

- ***NOTE: In the case that you find multiple modes, choose the color that appears first in alphabetical order***

 When you finish filling in the missing eye colors, please **display the `profiles_df`**

 **Outputs to be Graded**
 - Variable(s): `profiles_df`
 - Cell outputs

In [105]:
def common_eye(hair, skin):
    subset = profiles_df[(profiles_df['Hair_Color'] == hair) & (profiles_df['Skin_Color'] == skin)]
    modes = subset['Eye_Color'].mode()
    if len(modes) == 0:
        return None
    else:
        return sorted(modes)[0]

for i, row in profiles_df[profiles_df['Eye_Color'].isna()].iterrows():
    common_color = common_eye(row['Hair_Color'], row['Skin_Color'])
    if common_color is not None:
        profiles_df.at[i, 'Eye_Color'] = common_color
        

profiles_df
#print(profiles_df['Eye_Color'].isna.sum())

,ID,Name,Birthday,Location_during_crime,Eye_Color,Skin_Color,Hair_Color,Height,Age
0,P299,Marco Rossi,1969-10-07,fourth floor,red,indigo,orange,191,55
1,P086,Aarav Patel,1979-10-03,second floor,indigo,indigo,green,198,45
2,P022,Li Wei,1990-08-10,fourth floor,blue,red,violet,154,35
3,P003,Haruto Tanaka,1996-10-27,lobby,green,blue,violet,158,28
4,P036,Kwame Mensah,1991-02-26,fourth floor,blue,yellow,orange,184,34
...,...,...,...,...,...,...,...,...,...
343,P126,Andrew Choe,1988-01-03,NaN,violet,indigo,red,176,37
344,P203,Krish Thakker,1965-09-26,third floor,yellow,indigo,orange,193,60
345,P273,Jeonghan Yoon,2003-07-12,fourth floor,blue,indigo,red,193,22
346,P290,Ananya Malipeddi,1994-10-03,third floor,yellow,yellow,indigo,161,30
347,P233,Ifra Syed,1982-06-27,second floor,red,yellow,orange,169,43


## Q3) Finding the features of the culprit (43 PTS Total)

Now that we have successfully cleaned all of our data, lets begin finding the features of the criminal. Take a moment to look at the `Witnesses` table. We don't necessarily want all the statements from every single witness.

**NOTE:** Take a look at the structure of each statement, notice how there are only a few variations of statements from the witnesses.

**TASK 3.1 (5 Points):** Find all witnesses that were near the crime scene
- First load in the `Witness.csv` file and set it to a variable called `witness_df`
- create a new dataframe called `important_witnesses` that contains the id and the witness statements of those who were near the scene of the crime
- display the new dataframe when you are finished
- **HINT:** look at the floor which the crime happened on.

**Outputs to be Graded:**
- Variable(s): `witness_df`, `important_witnesses`
- Cell outputs

In [106]:
witness_df = pd.read_csv("Witness.csv")

merged = pd.merge(witness_df, profiles_df[['ID', 'Location_during_crime']], on='ID', how='inner')

important_witnesses = merged[merged['Location_during_crime'].str.lower() == 'second floor'][['ID', 'Statement']]

important_witnesses

       ID                                                Statement
13   P150        I saw someone with orange hair acting suspicious.
17   P075        I saw someone with orange hair acting suspicious.
21   P058         I saw someone with green eyes acting suspicious.
22   P157  I saw someone who looked 152 cm tall acting suspicious.
23   P157  I saw someone who looked 152 cm tall acting suspicious.
..    ...                                                      ...
329  P077        I saw someone with orange eyes acting suspicious.
330  P168           I saw someone with red skin acting suspicious.
331  P168           I saw someone with red skin acting suspicious.
345  P145        I saw someone with orange eyes acting suspicious.
346  P145        I saw someone with orange eyes acting suspicious.

[71 rows x 2 columns]

**TASK 3.2 (10 Points):** Find every potential eye color that the culprit could have

 - Put all the potential eye colors of the culprit in a list called `potential_eye_colors` and **display** it when you're done.
 - `potential_eye_colors` should have **no duplicates.**

 **Outputs to be Graded:**
 - Variable(s): `potential_eye_colors`
 - Cell outputs

In [107]:
merged2 = pd.merge(witness_df, profiles_df, on='ID', how='inner')

second_floor_witnesses = merged2[merged2['Location_during_crime'].str.lower() == 'second floor']
potential_eye_colors = second_floor_witnesses['Eye_Color'].dropna().unique().tolist()

potential_eye_colors

['red', 'orange', 'green', 'blue', 'indigo', 'yellow', 'violet']

**TASK 3.3 (5 Points):** Find every potential hair color that the culprit could have

 - Put all the potential hair colors of the culprit in a list called `potential_hair_colors` and **display** it when you're done.

**Outputs to be Graded**
- Variables: `potential_hair_colors`
- Cell outputs

In [108]:
potential_hair_colors = second_floor_witnesses['Hair_Color'].dropna().unique().tolist()

potential_hair_colors

['red', 'yellow', 'indigo', 'orange', 'blue', 'green', 'violet']

**TASK 3.4 (5 Points):** Find every potential skin color that the culprit could have

 - Put all the potential skin colors of the culprit in a list called `potential_skin_colors` and display it when you're done

**Outputs to be Graded**
- Variable(s): `potential_skin_colors`
- Cell outputs

In [109]:
potential_skin_colors = second_floor_witnesses['Skin_Color'].dropna().unique().tolist()

potential_skin_colors

['red', 'orange', 'indigo', 'yellow', 'blue', 'violet', 'green']

**TASK 3.5 (10 Points):** Find the potential height of the culprit

 - Put the smallest and largest potential heights of the culprit in the variables called `smallest_height` and `largest_height` and display them when you are done

 **Outputs to be Graded**
 - Variables: `smallest_height`, `largest_height`
 - Cell outputs

In [110]:
smallest_height = second_floor_witnesses['Height'].min()
largest_height = second_floor_witnesses['Height'].max()

print(smallest_height, largest_height)

151 200

**TASK 3.6 (8 Points):** Find the potential age of the culprit

 - Put the smallest and largest potential age of the culprit in the variables called `smallest_age` & `largest_age` and display them when you are done

 **Outputs to be Graded**
 - Variable(s): `smallest_age`, `largest_age`
 - Cell outputs

In [111]:
smallest_age = second_floor_witnesses['Age'].min()
largest_age = second_floor_witnesses['Age'].max()

print(smallest_age, largest_age)

19 66

## Q4) Who owns the Ticket? (30 PTS Total)

**TASK 4.1 (2 Points):** Loading final dfs


Load in the `Zichao_s_Magic_Show.csv` into a dataframe called `show_df` and the `Interrogation_Statements.csv` into a dataframe called `interrogation_df` respectively and display them when you are done

**Outputs to be Graded**
- Variables: `show_df`, `interrogation_df`
- Cell outputs

In [112]:
show_df = pd.read_csv("Zichao_s_Magic_Show.csv")
interrogation_df = pd.read_csv("Interrogation_Statements.csv")

show_df, interrogation_df

(       ID  Ticket_Number
 0    P132       50269975
 1    P056       28120732
 2    P250       88051289
 3    P197       79545169
 4    P012       83521845
 ..    ...            ...
 146  P121       31341288
 147  P003       85008158
 148  P180       24491860
 149  P283       38524355
 150  P142        2238676

 [151 rows x 2 columns],
                      Name  \
 0    Kristopher Stoichkov
 1           Naman Nagelia
 2    Pranavh Vallabhaneni
 3               Stacy Sun
 4          Rina Kobayashi
 ..                    ...
 495             Ishan Kar
 496          Adrian Black
 497       Brittany Taylor
 498        William Miller
 499  Christopher Ferguson

                                                                                                                                                                                                                 Statement
 0                                   "Re%spe%cti%ng o%the%rs' be%lo%ngi%ngs i%s my pri%nci%ple%. Dr. Fa%rdi%na%'s i%te%ms a%re% sa%fe% wi%th me%; the%ft co%ntra%di%cts my va%lu%e%s e%nti%re%ly. Tru%st my i%nte%gri%ty."
 1                                      "I@'d ne@ve@r je@o@pa@rdi@ze@ my re@pu@ta@ti@o@n by ste@a@li@ng. Dr. Fa@rdi@na@'s tru@st ma@tte@rs mo@re@ tha@n a@ny ma@rke@r. A@ccu@sa@ti@o@ns a@re@ ba@se@le@ss a@nd u@nfa@i@r."
 2    "My pro^je^ct pre^se^nta^ti^o^n o^ccu^pi^e^d me^ i^n the^ e^ngi^ne^e^ri^ng ha^ll. I^ co^u^ldn't ha^ve^ e^nte^re^d Dr. Fa^rdi^na^'s ro^o^m-co^mple^te^ly u^nre^la^te^d lo^ca^ti^o^ns, co^nfi^rme^d by ti^me^sta^mps."
 3                                             "Thre$e$ co$nse$cu$ti$ve$ e$xa$ms dra$i$ne$d me$ tha$t da$y. Ste$a$li$ng a$ ma$rke$r? A$bsu$rd. Re$vi$e$w my e$xa$m sche$du$le$-i$t'll co$nfi$rm my pa$cke$d ti$me$li$ne$."
 4                                                    "I% wa%s o%ff-ca%mpu%s a%tte%ndi%ng a% fa%mi%ly e%ve%nt. Se%cu%ri%ty lo%gs a%nd wi%tne%sse%s ca%n ve%ri%fy my a%bse%nce%. Thi%s a%ccu%sa%ti%o%n i%s i%mpo%ssi%ble%."
 ..                                                                                                                                                                                                                    ...
 495                                                                                                                     "I$ sto$le$ i$t i$n 2024 a$nd bri$be$d the$ po$li$ce$ wi$th do$nu$ts. No$t me$ thi$s ti$me$. >:D"
 496                                                                              "I% wa%s bu%sy wi%th my pro%je%ct pre%se%nta%ti%o%n i%n a%no%the%r bu%i%ldi%ng. I% di%dn't e%ve%n ste%p i%nto% Dr. Fa%rdi%na%'s ro%o%m."
 497                                                 "I@ wa@s bu@sy wi@th my gro@u@p pro@je@ct me@e@ti@ng i@n a@ co@mple@te@ly di@ffe@re@nt bu@i@ldi@ng. I@ ca@n't te@le@po@rt i@nto@ Fa@rdi@na@'s O@ffi@ce@ tha@t fa@st."
 498                                                                                                          "I^ wa^sn't e^ve^n o^n ca^mpu^s tha^t da^y. Che^ck the^ a^tte^nda^nce^ lo^gs; yo^u^ wo^n't fi^nd my na^me^."
 499                                                                                       "Ste$a$li$ng? Tha$t's no$t i$n my na$tu$re$ a$t a$ll. I$ re$spe$ct e$ve$ryo$ne$'s pro$pe$rty, e$spe$ci$a$lly Dr. Fa$rdi$na$'s."

 [500 rows x 2 columns])

We're **so close** to figuring out the *last* and *final* clue to locate the culprit, but it looks like they are trying to beat us to it! What a devious criminal!

The culprit must have **sabotaged** our data after **interrogation** because it looks so wonky with weird symbols.

However, HQ informed us that our good friend and exemplar cryptanalyst **Alan Turing** has something to say to help us fix the data. **He encoded his message to keep it safe from the culprit.**

**TASK 4.2 (10 Points):**

Find what **Alan Turing** has to say:
- Use the `interrogation_df` to locate Alan's Turing's message.
- Put the message in a variable called `encoded_message` as a string (**Exclude** any **quotation marks** within the statement)
 - **Print** the encoded message in the following format: {"Encoded Message:", encoded_message}
- Figure out what the message says by taking a look at the numbers:
 - A **single space** between numbers indicates a letter to form a word.
 - A **double space** between numbers indicates the start of a new word.
- Store his decoded message in a variable called `decoded_message`
- Print out **Alan Turing's** decoded message in the following format: {"Decoded Message:", decoded_message}

**Outputs to be Graded**
- Variable(s): `encoded_message`, `decoded_message`
- Cell outputs: The two **formatted** messages

In [113]:
encoded_message = interrogation_df.loc[
    interrogation_df['Name'].str.lower() == 'alan turing', 'Statement'
].iloc[0]

print({"Encoded Message:": encoded_message})
encoded_message = encoded_message.strip('"') # i was getting some weird error if i didnt do this, had to do with a trailing " i think??

decoded_message = []
for word in encoded_message.split('  '):
    letters = ''.join(chr(int(num) + 64) for num in word.split())
    decoded_message.append(letters)

decoded_message = ' '.join(decoded_message)
print({"Decoded Message:": decoded_message})

{'Encoded Message:': '"20 8 5  16 1 20 20 5 18 14  9 19  20 15  3 12 5 1 14  21 16  20 8 5  6 9 12 5  2 25  18 5 13 15 22 9 14 7  1 6 20 5 18  5 1 3 8  22 15 23 5 12  20 8 5  19 25 13 2 15 12 19  16 5 18 3 5 14 20  4 15 12 12 1 18  3 1 18 18 15 20  1 20"'}
{'Decoded Message:': 'THE PATTERN IS TO CLEAN UP THE FILE BY REMOVING AFTER EACH VOWEL THE SYMBOLS PERCENT DOLLAR CARROT AT'}

**TASK 4.3 (10 Points):** **Restore** the interrogation statements back to their original state after **following the decoded message from before**.
- After restoration, make sure your modifications are updated in the `interrogation_df` itself.
- **Display** the `interrogation_df` when you are done.

**Outputs to be Graded:**
- Variable(s): `interrogation_df`
- Cell outputs

In [114]:
def restore_statement(text):
    text = str(text)
    cleaned = ""
    i = 0
    while i < len(text):
        current_char = text[i]
        if current_char.lower() in "aeiou" and i + 1 < len(text) and text[i+1] in "%$^@":
            cleaned += current_char
            while i + 1 < len(text) and text[i+1] in "%$^@":
                i += 1
        else: 
            cleaned += current_char
        i+=1
    return cleaned

interrogation_df['Statement'] = interrogation_df['Statement'].apply(restore_statement)
interrogation_df

,Name,Statement
0,Kristopher Stoichkov,"""Respecting others' belongings is my principle. Dr. Fardina's items are safe with me; theft contradicts my values entirely. Trust my integrity."""
1,Naman Nagelia,"""I'd never jeopardize my reputation by stealing. Dr. Fardina's trust matters more than any marker. Accusations are baseless and unfair."""
2,Pranavh Vallabhaneni,"""My project presentation occupied me in the engineering hall. I couldn't have entered Dr. Fardina's room-completely unrelated locations, confirmed by timestamps."""
3,Stacy Sun,"""Three consecutive exams drained me that day. Stealing a marker? Absurd. Review my exam schedule-it'll confirm my packed timeline."""
4,Rina Kobayashi,"""I was off-campus attending a family event. Security logs and witnesses can verify my absence. This accusation is impossible."""
...,...,...
495,Ishan Kar,"""I stole it in 2024 and bribed the police with donuts. Not me this time. >:D"""
496,Adrian Black,"""I was busy with my project presentation in another building. I didn't even step into Dr. Fardina's room."""
497,Brittany Taylor,"""I was busy with my group project meeting in a completely different building. I can't teleport into Fardina's Office that fast."""
498,William Miller,"""I wasn't even on campus that day. Check the attendance logs; you won't find my name."""
499,Christopher Ferguson,"""Stealing? That's not in my nature at all. I respect everyone's property, especially Dr. Fardina's."""


**TASK 4.4 (8 Points):** Create a column called `Ticket_Color` for the `show_df` that displays all the colors of the ticket

- Remember that there was a show ticket left at the crime scene, take a second to look through `show_df`. Try and find a way to identify how you can find the ticket color from the ticket number.
- **Display** the `show_df` when you are done
- **HINT:** examine the `interrogation_df`

**Output to be Graded**
- Variable(s): `show_df`
- Cell outputs

In [115]:
mask = interrogation_df['Statement'].str.contains('ticket', case=False, na=False)
pd.set_option('display.max_colwidth', None)

interrogation_df[mask]

#364	Monkey D Luffy	"Sum the individual #s in ticket numbers, look at the rightmost value, 0-2:B, 3-5:R , 6-7:G, 8-9:Y"

show_df = pd.read_csv("Zichao_s_Magic_Show.csv")

def ticket_color(number):
    ticket_str = str(number)

    total = 0
    for digit in ticket_str:
        total += int(digit)
        
    last_digit = total % 10
    
    if last_digit <= 2:
        color = "Blue"
    elif last_digit <= 5:
        color = "Red"
    elif last_digit <= 7:
        color = "Green"
    else:
        color = "Yellow"
        
    return color

show_df["Ticket_Color"] = show_df["Ticket_Number"].apply(ticket_color)

print(show_df)

       ID  Ticket_Number Ticket_Color
0    P132       50269975          Red
1    P056       28120732          Red
2    P250       88051289         Blue
3    P197       79545169        Green
4    P012       83521845        Green
..    ...            ...          ...
146  P121       31341288         Blue
147  P003       85008158          Red
148  P180       24491860          Red
149  P283       38524355          Red
150  P142        2238676          Red

[151 rows x 3 columns]

## Q5) Finding the culprit (12 PTS Total)

A helpful function might be the "iloc" function. Have a look at: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html

**TASK 5.1(10 Points):** Using all the **data compiled from before** find a person that matches all the features from the profile.

- Do not hardcode or you will lose credit after all your hardwork 🥸

- Put the name of the culprit in a variable called `culprit`
- **Print** out the name of the culprit (There is only one).

**Outputs to be Graded**
- Variable(s): `culprit`
- Cell outputs

In [116]:
combined = pd.merge(profiles_df, show_df, on="ID", how ="left")

suspects = combined.query(
    "Location_during_crime.str.lower() == 'second floor' and "
    "Eye_Color in @potential_eye_colors and "
    "Hair_Color in @potential_hair_colors and "
    "Height >= @smallest_height and "
    "Height <= @largest_height and "
    "Age >= @smallest_age and "
    "Age <= @largest_age and "
    "Ticket_Color == @crime_ticket_color"
)

culprit = suspects["Name"].iloc[0]
print(culprit)

#Giovanni Moretti

Giovanni Moretti

**TASK 5.2 (2 Points):** Check if your culprit is correct!
- **Interrogate** your culprit to see if you got the correct person.
- **Print** out their entire statement.

**Outputs to be Graded:**
- Cell output (the entire statement)

In [ ]:
culprit_statement = interrogation_df.loc[
    interrogation_df["Name"].str.lower() == culprit.lower(), "Statement"
].iloc[0]

print(culprit_statement)
#this contradicts their profile, which says they were on the 2nd floor at the time of the incident. liar!!!!!!!!!

"I was at a family reunion off-campus. Photos and witnesses prove my absence. Investigate thoroughly."

# GREAT WORK DETECTIVE!! 🌻

## BONUS (1 point)
We have shared an online interactive textbook for CMSC320: Introduction to Data Science. The textbook is still in progress, and more chapters will be published gradually throughout the semester.

This short pre-feedback survey will help us understand your experience, preferences, and expectations regarding the textbook format before you start using it.

Here is the link to the survey: https://forms.gle/n3Nbmeosoos7tjFa9


Here is the link to the textbook:
 https://ffalam.github.io/CMSC320TextBook/index.html

Note: After completing the survey, please take a screenshot of your submission and submit it as proof of participation.

This is the bonus question for this assignment only.

![Form submission](NVIDIA_Overlay_OHmuKXnSrp.png)